version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ${HOME}/Documentos/Docker/servlet-example/PostgreSQL/servlet-example:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  jsp-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-compose
    ports:
      - "8089:8080"

      
